services:
  sense:
    image: main:${IMAGE_TAG:-local}
    container_name: sense
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8051:8051"
    env_file:
      - .env
  sense_admin:
    image: main:${IMAGE_TAG:-local}
    container_name: admin
    ports:
      - "1234:1234"
    env_file:
      - .env.admin
  metabase:
    image: metabase/metabase:v0.49.2
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_HOST: sense_db
      MB_DB_USER: metabase_user
      MB_DB_PASS: 'password'
  langfuse:
    image: langfuse/langfuse:2.93.8
    container_name: langfuse
    ports:
      - "1235:3000"
    env_file:
      - .env.langfuse
  sense_db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/full_suite_sql_inits:/docker-entrypoint-initdb.d
      - sense-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'password'
  sense_cache:
    image: redis
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - sense-cache:/data

volumes:
  sense-db:
    driver: local
  sense-cache:
    driver: local